site_name: OpenSource ｜ EdurtIO
site_url: https://opensource.edurt.io/
site_author: qinamoQ
site_description: >-
  Committed to building friendly open source projects

repo_name: EdurtIO/opensource.edurt.io
repo_url: https://github.com/EdurtIO/opensource.edurt.io
edit_uri: "https://github.com/EdurtIO/opensource.edurt.io/docs"

copyright: Copyright &copy; 2022 EdurtIO

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/open-source-initiative
  favicon: material/open-source-initiative

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EdurtIO
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/qianmoQ/

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

use_directory_urls: false

extra_css:
  - stylesheets/extra.css

plugins:
  - search

  - tags:
      tags_file: tags.md

  - i18n:
      default_language: en
      languages:
        en: English
      nav_translations:
        en:
          project_index: Project Index
          project_dbm: DBM (DataBase GUI)

  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

  - git-committers:
      repository: EdurtIO/opensource.edurt.io

  - redirects:
      redirect_maps:
        publish-project-new.md: project/dbm.md

nav:
  - Home: index.md
  - Projects: 
      - project_index: projects.md
      - project_dbm: project/dbm.md
